Repository Hydronium-ion/Rare-Client, pull requests merged in 2020-08, with the labels that each got.

#55 [#54] CSS Layout
  public/style.css
  src/App.tsx
  src/components/CardList/CardList.component.tsx
  src/components/CardList/CardList.styles.tsx
  src/components/Custom/Card/Card.styles.tsx
  src/components/Header/Header.component.tsx
  src/components/Header/Header.styles.tsx
  src/components/MyBlog/TagList/TagList.styles.tsx
  src/components/Navigation/Navigation.styles.tsx
  src/components/Posts/Bookmark/Bookmark.styles.tsx
  src/components/Posts/Likes/Likes.styles.tsx
  src/pages/Main/Main.component.tsx
  src/pages/Main/Main.styles.tsx
  src/pages/MyBlog/MyBlog.styles.tsx
  src/pages/Posts/Posts.styles.tsx
  src/pages/Profile/Profile.styles.tsx
  src/pages/Write/Write.styles.tsx
  src/styles/GlobalTheme.component.tsx
  src/styles/PageContainer.styles.tsx
  src/styles/theme.ts
Labels: style

#59 [#52] Comment Component
  src/components/Posts/Comments/Comment.data.ts
  src/components/Posts/Comments/CommentItem.component.tsx
  src/components/Posts/Comments/CommentItem.style.tsx
  src/components/Posts/Comments/Comments.component.tsx
  src/components/Posts/Comments/CommentsList.component.tsx
  src/components/Posts/Comments/CommentsList.style.tsx
  src/components/Posts/Comments/CommentsTemplate.component.tsx
  src/types/Comment.ts
  src/utils/formatDate.ts
Labels: feature

#60 [#58] 전반적인 CSS 스타일 수정
  .env.development
  .env.production
  public/index.html
  public/style.css
  src/App.tsx
  src/components/CardList/CardList.component.tsx
  src/components/Common/Modal/Modal.component.tsx
  src/components/Common/Modal/Modal.styles.tsx
  src/components/Common/Portal/Portal.component.tsx
  src/components/Custom/Card/SkeletonCard.styles.tsx
  src/components/Custom/Icon/svg/facebook.svg
  src/components/Custom/Icon/svg/github.svg
  src/components/Custom/Icon/svg/google.svg
  src/components/Custom/Icon/svg/index.ts
  src/components/Custom/Modal/Layout.component.tsx
  src/components/Custom/Modal/Layout.styles.tsx
  src/components/Custom/Modal/Login/Login.component.tsx
  src/components/Custom/Modal/Login/Login.styles.tsx
  src/components/Custom/Modal/Modal.component.tsx
  src/components/Header/Header.component.tsx
  src/components/Header/Header.styles.tsx
  src/components/Navigation/Navigation.styles.tsx
  src/store/blog/blog.sagas.ts
  src/store/modal/modal.actions.ts
  src/store/modal/modal.reducer.ts
  src/store/modal/modal.types.ts
  src/store/post/post.sagas.ts
  src/store/rootReducer.ts
  src/styles/PageContainer.styles.tsx
  src/types/Modal.ts
Labels: component, style

#62 [#61] Card와 Post 연결
  src/App.tsx
  src/components/Custom/Card/Card.component.tsx
  src/components/Custom/Card/SkeletonCard.component.tsx
  src/components/Custom/Card/SkeletonCard.styles.tsx
  src/components/Custom/Dropdown/Dropdown.component.tsx
  src/components/Custom/Dropdown/Dropdown.styles.tsx
  src/hooks/useFetch.tsx
  src/pages/Post/Post.component.tsx
  src/pages/Post/Post.data.ts
  src/pages/Post/Post.styles.tsx
  src/pages/Post/SkeletonPost.component.tsx
  src/pages/Post/SkeletonPost.styles.tsx
  src/pages/Posts/Posts.component.tsx
  src/stories/post/post.stories.tsx
  src/types/Post.ts
Labels: component

#68 [#52] Comment 서버통신에 필요한 Action, Reducer, Type 생성
  src/components/Posts/Bookmark/Bookmark.component.tsx
  src/components/Posts/Comments/Comment.data.ts
  src/components/Posts/Comments/CommentItem.component.tsx
  src/components/Posts/Comments/Comments.component.tsx
  src/components/Posts/Comments/CommentsList.component.tsx
  src/store/blog/blog.reducer.ts
  src/store/comment/comment.actions.ts
  src/store/comment/comment.reducer.ts
  src/store/comment/comment.sagas.ts
  src/store/comment/comment.types.ts
  src/types/Comment.ts
Labels: feature

#71 [#69 #70] Tag / Search / PostCard Component 생성
  src/App.tsx
  src/components/Common/PostCard/PostCard.component.tsx
  src/components/Common/PostCard/PostCard.styles.tsx
  src/components/Common/PostCard/PostCardList.component.tsx
  src/components/Custom/Input/Input.component.tsx
  src/components/Custom/Input/Input.styles.tsx
  src/components/Custom/Tag/Tag.component.tsx
  src/components/Header/Header.component.tsx
  src/components/MyBlog/Contents/Contents.component.tsx
  src/components/Tag/TagList.component.tsx
  src/components/Tag/TagList.styles.tsx
  src/pages/Search/Search.component.tsx
  src/pages/Search/Search.data.ts
  src/pages/Search/Search.styles.tsx
  src/pages/Search/SearchResult.component.tsx
  src/pages/Search/SearchResultInfo.component.tsx
  src/pages/Search/SearchResultInfo.styles.tsx
  src/pages/Tag/Tag.component.tsx
  src/pages/Tag/Tag.styles.tsx
  src/types/Post.ts
Labels: feature

#75 Post 무한 스크롤링
  src/components/CardList/CardList.component.tsx
  src/store/blog/blog.actions.ts
  src/store/blog/blog.reducer.ts
  src/store/blog/blog.sagas.ts
  src/store/blog/blog.types.ts
Labels: component
