Repository Hydronium-ion/Rare-Client, pull requests merged in 2020-07, with the labels that each got.

#7 [#3] main page layout
  .gitignore
  src/App.tsx
  src/Pages/Main/Main.component.tsx
  src/Pages/Main/Main.styles.tsx
  src/components/CardList/CardList.component.tsx
  src/components/CardList/CardList.data.ts
  src/components/CardList/CardList.styles.tsx
  src/components/Custom/Avatar/Avatar.component.tsx
  src/components/Custom/Avatar/Avatar.styles.tsx
  src/components/Custom/Button/Button.component.tsx
  src/components/Custom/Button/Button.styles.tsx
  src/components/Custom/Card/Card.component.tsx
  src/components/Custom/Card/Card.data.ts
  src/components/Custom/Card/Card.styles.tsx
  src/components/Custom/Icon/Icon.component.tsx
  src/components/Custom/Icon/svg/bell.svg
  src/components/Custom/Icon/svg/clock.svg
  src/components/Custom/Icon/svg/down-arrow.svg
  src/components/Custom/Icon/svg/fire.svg
  src/components/Custom/Icon/svg/index.ts
  src/components/Custom/Icon/svg/likes.svg
  src/components/Custom/Icon/svg/lock.svg
  src/components/Custom/Icon/svg/rare.svg
  src/components/Custom/Icon/svg/search.svg
  src/components/Custom/Icon/svg/unlock.svg
  src/components/Custom/Icon/svg/views.svg
  src/components/Custom/Input/Input.tsx
  src/components/Header/Header.component.tsx
  src/components/Header/Header.styles.tsx
  src/components/Navigation/Navigation.component.tsx
  src/components/Navigation/Navigation.styles.tsx
  src/components/PopularTags/PopularTags.component.tsx
  src/components/PopularTags/PopularTags.data.ts
  src/components/PopularTags/PopularTags.styles.tsx
  src/stories/Custom/Avatar/Avatar.stories.tsx
  src/stories/Custom/Button/Button.stories.tsx
  src/stories/Custom/Card/Card.stories.tsx
  src/stories/Header/Header.stories.tsx
  src/styles/GlobalStyle.tsx
  yarn.lock
Labels: feature

#16 [#3] main page layout
  .storybook/main.js
  package.json
  public/style.css
  src/App.tsx
  src/Pages/Main/Main.component.tsx
  src/Pages/Main/Main.styles.tsx
  src/Pages/Search/Search.component.tsx
  src/Pages/Search/Search.styles.tsx
  src/components/CardList/CardList.component.tsx
  src/components/Custom/Avatar/Avatar.styles.tsx
  src/components/Custom/Button/Button.styles.tsx
  src/components/Custom/Card/Card.component.tsx
  src/components/Custom/Input/Input.component.tsx
  src/components/Custom/Input/Input.styles.tsx
  src/components/Header/Header.component.tsx
  src/components/Header/Header.styles.tsx
  src/components/Navigation/Navigation.component.tsx
  src/components/Navigation/Navigation.styles.tsx
  src/components/PopularTags/PopularTags.component.tsx
  src/index.tsx
  src/stories/Custom/Avatar/Avatar.stories.tsx
  src/stories/Custom/Button/Button.stories.tsx
  src/stories/Custom/Card/Card.stories.tsx
  src/stories/Custom/Input/Input.stories.tsx
  src/stories/Header/Header.stories.tsx
  src/styles/GlobalStyle.tsx
  src/utils/util.ts
  tsconfig.json
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: feature

#17 [#15] 무한스크롤 구현
  src/components/CardList/CardList.component.tsx
  src/components/CardList/CardList.data.ts
  src/components/Custom/Card/Card.component.tsx
  src/components/Custom/Dropdown/Dropdown.component.tsx
  src/components/Custom/Dropdown/Dropdown.styles.tsx
  src/components/Header/Header.component.tsx
  src/components/Header/Header.styles.tsx
  src/hooks/useFocusOutEvent.tsx
  src/stories/Custom/Card/Card.stories.tsx
  src/stories/Custom/Dropdown/Dropdown.stories.tsx
  src/styles/GlobalStyle.tsx
Labels: feature

#13 [#6] Feat : CI/CD 구축
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  appspec.yml
  deploy.sh
Labels: environment

#19 [Header Component Test #18] Header Component U.I. Testing
  jest.config.js
  src/__mocks__/fileMock.ts
  src/components/Custom/Avatar/Avatar.component.tsx
  src/components/Custom/Dropdown/Dropdown.styles.tsx
  src/stories/Header/Header.stories.tsx
  tests/Header.test.tsx
  tsconfig.json
Labels: style, test

#22 [#21] 내 블로그 Page 작성
  public/index.html
  src/App.tsx
  src/pages/MyBlog/MyBlog.component.tsx
  src/pages/MyBlog/MyBlog.styles.tsx
Labels: component

#23 [#20] 블로그 읽기 Page 작성
  src/App.tsx
  src/pages/Posts/Posts.component.tsx
  src/pages/Posts/Posts.styles.tsx
Labels: component

#26 [#25] 블로그 읽기에 필요한 ui 구성
  src/components/Custom/Avatar/Avatar.styles.tsx
  src/components/Custom/Icon/svg/index.ts
  src/components/Custom/Icon/svg/left-arrow.svg
  src/components/Custom/Icon/svg/right-arrow.svg
  src/pages/Posts/Posts.component.tsx
  src/pages/Posts/Posts.data.ts
  src/pages/Posts/Posts.styles.tsx
Labels: component, feature, style

#31 [#28] Profile Page 작성
  src/App.tsx
  src/pages/Profile/Profile.component.tsx
  src/pages/Profile/Profile.styles.tsx
Labels: component

#33 [#32] Custom Toggle Button 작성
  src/components/Custom/ToggleButton/ToggleButton.component.tsx
  src/components/Custom/ToggleButton/ToggleButton.styles.tsx
  src/stories/Custom/ToggleButton/ToggleButton.stories.tsx
Labels: component

#27 [#24] '내 블로그' Page에 필요한 ui 구성
  .storybook/main.js
  jest.config.js
  src/App.tsx
  src/components/CardList/CardList.data.ts
  src/components/Custom/Tag/Tag.component.tsx
  src/components/Custom/Tag/Tag.styles.tsx
  src/components/MyBlog/Contents/Contents.component.tsx
  src/components/MyBlog/Contents/Contents.styles.tsx
  src/components/MyBlog/Navigation/Navigation.component.tsx
  src/components/MyBlog/Navigation/Navigation.styles.tsx
  src/components/MyBlog/TagList/TagList.component.tsx
  src/components/MyBlog/TagList/TagList.styles.tsx
  src/components/MyBlog/UserProfile/UserProfile.component.tsx
  src/components/MyBlog/UserProfile/UserProfile.styles.tsx
  src/components/Navigation/Navigation.component.tsx
  src/hooks/useSelectActives.tsx
  src/pages/MyBlog/MyBlog.component.tsx
  src/pages/MyBlog/MyBlog.styles.tsx
  src/styles/GlobalStyle.tsx
  src/utils/util.ts
  tsconfig.json
  webpack.dev.js
  webpack.prod.js
Labels: component, style

#39 [#38] 공용으로 사용될 Modal, Portal 컴포넌트 작성
  public/index.html
  src/components/Common/Modal/Modal.component.tsx
  src/components/Common/Modal/Modal.styles.tsx
  src/components/Common/Portal/Portal.component.tsx
  src/pages/Write/Upload.component.tsx
  src/pages/Write/Write.component.tsx
Labels: component

#41 [#40] Upload Component 작성
  src/components/Common/Modal/Modal.component.tsx
  src/components/Common/Modal/Modal.styles.tsx
  src/components/Custom/Icon/svg/close.svg
  src/components/Custom/Icon/svg/globe.svg
  src/components/Custom/Icon/svg/index.ts
  src/components/Custom/Icon/svg/lock.svg
  src/components/Custom/Icon/svg/picture.svg
  src/pages/Write/Upload.component.tsx
  src/pages/Write/Upload.styles.tsx
  src/stories/Custom/Button/Button.stories.tsx
  src/styles/GlobalStyle.tsx
Labels: component

#44 [#43] Post Page Component 분리
  package.json
  src/components/Posts/Bookmark/Bookmark.component.tsx
  src/components/Posts/Bookmark/Bookmark.styles.tsx
  src/components/Posts/Comments/Comments.component.tsx
  src/components/Posts/Comments/Comments.styles.tsx
  src/components/Posts/Likes/Likes.component.tsx
  src/components/Posts/Likes/Likes.styles.tsx
  src/components/Posts/Links/Links.component.tsx
  src/components/Posts/Links/Links.styles.tsx
  src/components/Posts/Links/PostBox/PostBox.component.tsx
  src/components/Posts/Links/PostBox/PostBox.styles.tsx
  src/components/Posts/UserProfile/UserProfile.component.tsx
  src/components/Posts/UserProfile/UserProfile.styles.tsx
  src/pages/Posts/Posts.component.tsx
  src/pages/Posts/Posts.styles.tsx
  yarn.lock
Labels: refactoring

#46 redux 기본 환경 설정
  package.json
  src/components/CardList/CardList.component.tsx
  src/components/Custom/Card/Card.component.tsx
  src/components/Custom/Card/Card.data.ts
  src/index.tsx
  src/store/blog/blog.actions.ts
  src/store/blog/blog.reducer.ts
  src/store/blog/blog.sagas.ts
  src/store/blog/blog.types.ts
  src/store/index.ts
  src/store/rootReducer.ts
  src/store/rootSaga.ts
  yarn.lock
Labels: data

#51 [#49] 포스트 작성
  .env.development
  src/pages/Write/Upload.component.tsx
  src/store/post/post.actions.ts
  src/store/post/post.reducer.ts
  src/store/post/post.sagas.ts
  src/store/post/post.types.ts
  src/store/rootReducer.ts
  src/store/rootSaga.ts
  src/types/Post.ts
Labels: feature
